### ISSUE TITLE
State province

### ISSUE THREAD

**Issue by Walter-Correa** [George480/geolite#2]
Can I get the state province with this include?

**Comment by George480** [comment]
These are the data the original database provides with an example:

1. **geoname_id:** 579870
2. **locale_code:** en
3. **continent_code:** EU 
4. **continent_name:** Europe 
5. **country_iso_code:** RU 
6. **country_name:** Russia 
7. **subdivision_1_iso_code:** MOW 
8. **subdivision_1_name:** Moscow 
9. **subdivision_2_iso_code:** 
10. **subdivision_2_name:** 
11. **city_name:** Babushkin 
12. **metro_code:** 
13. **time_zone:** Europe/Moscow
14. **is_in_european_union:** 0

**Comment by Walter-Correa** [comment]
But what is state/province of Babushkin? Moscow?
If yes, can you create GetPlayerState(playerid...  ? 

Using subdivision_1_name:

**Comment by George480** [comment]
I can try creating a separate database but the file size will be increased.

**Comment by Walter-Correa** [comment]
> I can try creating a separate database but the file size will be increased.

**This include is so great!**
I don't care about file size, if you can, create it and I will use this include forever!

EDIT: The function need to be **GetPlayerProvince** because **GetPlayerState** is a samp function!

**Comment by George480** [comment]
I decided not to include parts of city database (timezone for example) but only the province you requested for in a separate. `geoname_id` differs for many of them with same name so I will have to create a unique one myself. I will try to get it working for the next update on 3rd June.

**Comment by Walter-Correa** [comment]
> I decided not to include parts of city database (timezone for example) but only the province you requested for in a separate. `geoname_id` differs for many of them with same name so I will have to create a unique one myself. I will try to get it working for the next update on 3rd June.

Thank you so much!

**Comment by George480** [comment]
Added. For any upcoming issues, feel free to open a new issue.

**Comment by Walter-Correa** [comment]
> Added. For any upcoming issues, feel free to open a new issue.

Woooow Great. Thank you so much!
